name: Tests and Linting

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Validate code formatting with Spotless
        run: ./gradlew spotlessCheck

      - name: Build and test
        run: ./gradlew build --no-daemon

      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: build/reports/tests/test

  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Commitlint
        run: npm install --save-dev @commitlint/{config-conventional,cli}

      - name: Create Commitlint config
        run: |
          echo '{"extends": ["@commitlint/config-conventional"]}' > .commitlintrc.json

      - name: Check commit messages
        run: |
          git log origin/main..HEAD --pretty=format:'%s' | npx commitlint --verbose

      - name: Check PR title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "$PR_TITLE" | npx commitlint --verbose
